package com.whistle.needhi.enums;

public enum Location {
    BHELPUR, EZHIL_NAGAR, GANESAPURAM, KEELA_KUMARESAPURAM, KRISHNASAMUTHIRAM, MELA_KUMARESAPURAM, TAMIL_NAGAR, THIRUVENKADA_NAGAR, VALLALAAR_NAGAR;
}
